name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [master] # Или 'master', в зависимости от вашей ветки

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Даёт доступ к записи в ветку gh-pages

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Create Gemfile if missing
        run: |
          if [ ! -f Gemfile ]; then
            echo 'source "https://rubygems.org"' > Gemfile
            echo 'gem "jekyll"' >> Gemfile
          fi

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl ""
